# Generated by Django 6.0.2 on 2026-03-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(blank=True, help_text='Hex color code, e.g. #1a2b3c', max_length=7)),
                ('footer_enabled', models.BooleanField(default=False)),
                ('resources_text', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
    ]
